
[package]
name = "dinosaur-e2e"
version = "0.0.1"
edition = "2021"
build = "build.rs"

[dependencies]
bevy = { version = "*", default-features = false, features = ["bevy_app"] }
log = { workspace = true }
dinosaur-game = { path = "../game" }
