name: 'CI Failure Feedback'
description: 'Post CI failure feedback comment to PR when a job fails'
inputs:
  github-token:
    description: 'GitHub token with PR write permissions (use COPILOT_INVOKER_TOKEN for @copilot mentions)'
    required: true
  job-name:
    description: 'Display name of the failed job (the "name:" value in the workflow YAML, NOT the job ID). Example: "Test Suite on Linux"'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          scripts/node_modules
        key: ${{ runner.os }}-bun-scripts-${{ hashFiles('scripts/bun.lock', 'scripts/package.json') }}
        restore-keys: |
          ${{ runner.os }}-bun-scripts-

    - name: Install Scripts Dependencies
      shell: bash
      working-directory: scripts
      run: bun install --frozen-lockfile || bun install

    - name: Post CI Feedback
      shell: bash
      working-directory: scripts
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        JOB_NAME: ${{ inputs.job-name }}
        RUN_ID: ${{ github.run_id }}
        # Use PR head SHA; fallback to github.sha for non-PR events (though this action is PR-only)
        HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        WORKFLOW_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: bun run main.ts ci-feedback-post-job
