pub mod app;
mod camera;
pub mod components;
mod debug;
mod dino;
mod game_control;
mod game_logic;
mod game_over;
mod game_start;
mod ground;
mod resources;
mod screens;
mod tree;
pub mod utils;
mod windows_handler;

pub use camera::setup_2d_camera;
pub use debug::DebugPlugin;
pub use dino::DinoPlugin;
pub use game_control::GameControlPlugin;
pub use game_logic::GameLogicPlugin;
pub use game_over::GameOverPlugin;
pub use game_start::GameStartPlugin;
pub use ground::GroundPlugin;
pub use resources::*;
pub use screens::GameScreen;
pub use tree::TreePlugin;
pub use windows_handler::*;
