pub mod app;
mod camera;
pub mod components;
mod dino;
mod game_control;
mod game_logic;
mod game_start;
mod ground;
mod resources;
mod screens;
mod tree;
pub mod utils;
mod windows_handler;

pub use camera::normal_app_setup;
pub use dino::DinoPlugin;
pub use game_control::GameControlPlugin;
pub use game_logic::GameLogicPlugin;
pub use game_start::GameStartPlugin;
pub use ground::GroundPlugin;
pub use resources::*;
pub use screens::GameScreen;
pub use tree::TreePlugin;
pub use windows_handler::*;
